### ISSUE TITLE
How to browserify fluentReports?

### ISSUE THREAD

**Issue by risoldi** [NathanaelA/fluentreports#15]
Hello,

I tried to use browserify to bundle up fluentreports in a js that can run in the browser, however I ran into some problems. Here's what I did: I installed fluentreports, pdfkit, blob-stream into node.js, then in the fluentreports downloaded directory, I ran:

browserify lib/fluentReports.js -o fr-bundle.js

However, here's what I got:

SyntaxError: Line 92: Unexpected token ILLEGAL while parsing /Users/mar/Downloads/fluentreports-master/node_modules/pdfkit/js/font.js
    at Stream.end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:71:21)
    at _end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:505:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
    at /usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:942:16
    at process._tickCallback (node.js:419:13)

I'm very new at node.js, and am not sure whether all node modules can work with browserify. Care to give a hand?

Thanks a lot in advance.
Best regards,
M.

**Comment by NathanaelA** [comment]
Just for those who care; the latest versions do work fully with browserify.   The demo site; http://www.fluentreports.com uses browserify to build the file.
