### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by johntom** [NathanaelA/fluentreports#85]
Hi,
1) When I add comment lines to http://www.fluentreports.com/demo.html all works as expected.
i.e the modifications creates a 3 page report and prints the header on 3 pages.
if I try the same thing running locally in nodejs when I add the extra comments 

```
============= code 
  rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
          rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
          rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
          rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.newLine();
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
        rpt.print(data.comments);
```
and it goes to a 2nd page I get error below
```
options undefined
REPORTAPI: Error running header in report ReportError {
  error: TypeError: Cannot read property 'number_of_pages' of null
    at ReportHeaderFooter.header [as _part] (D:\trails\MAS\trails-mas\api\services\FluentService.js:79:23)
    at _handleCallingDetailFunction (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1382:34)
    at _handlePrePageBreak (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1346:21)
    at ReportHeaderFooter.run (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1448:17)
    at printFoundHeaders (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:3242:28)
    at ReportRenderer._handleHeader (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:3247:17)
    at ReportRenderer.newPage (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:2142:22)
    at ReportRenderer.print (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:2523:30)
    at ReportHeaderFooter.header [as _part] (D:\trails\MAS\trails-mas\api\services\FluentService.js:132:13)
    at _handleCallingDetailFunction (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1382:34)
    at _handlePrePageBreak (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1346:21)
    at ReportHeaderFooter.run (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1448:17)
    at groupChangeCallback (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:5174:38)
    at ReportGroup._renderIt (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:5210:21)
    at groupContinue (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:3890:33)
    at renderData (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:3915:17)
    at ReportDataSet._renderIt (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:3958:21)
    at renderGroup (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:4184:41)
    at ReportSection._renderIt (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:4192:13)
    at D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1256:33
    at Report._renderPart (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1202:17)
    at Report._renderIt (D:\trails\MAS\trails-mas\api\lib\fluentReports.js:1219:18),
  stack: 'TypeError: Cannot read property \'number_of_pages\' of null\n    at ReportHeaderFooter.header [as _part] (D:\\trails\\MAS\\trails-mas\\api\\services\\FluentService.js:79:23)\n    at _handleCallingDetailFunction (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1382:34)\n    at _handlePrePageBreak (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1346:21)\n    at ReportHeaderFooter.run (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1448:17)\n    at printFoundHeaders (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:3242:28)\n    at ReportRenderer._handleHeader (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:3247:17)\n    at ReportRenderer.newPage (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:2142:22)\n    at ReportRenderer.print (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:2523:30)\n    at ReportHeaderFooter.header [as _part] (D:\\trails\\MAS\\trails-mas\\api\\services\\FluentService.js:132:13)\n    at _handleCallingDetailFunction (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1382:34)\n    at _handlePrePageBreak (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1346:21)\n    at ReportHeaderFooter.run (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1448:17)\n    at groupChangeCallback (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:5174:38)\n    at ReportGroup._renderIt (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:5210:21)\n    at groupContinue (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:3890:33)\n    at renderData (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:3915:17)\n    at ReportDataSet._renderIt (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:3958:21)\n    at renderGroup (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:4184:41)\n    at ReportSection._renderIt (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:4192:13)\n    at D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1256:33\n    at Report._renderPart (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1202:17)\n    at Report._renderIt (D:\\trails\\MAS\\trails-mas\\api\\lib\\fluentReports.js:1219:18)' }
```
2) Also if I try to use the same code in demo an error is raised on pipeStream so I assume pipeStream is not predfined running locally.
```
  // Create a new Report Engine
  // pipeStream is predefined in this report to make it display in the browser
var rpt = new Report(pipeStream);


```
3) This is my first time in a long time testing fluentreports and I will read the docs and test again.
Thanks
John

**Comment by NathanaelA** [comment]
The browser demo code (as-is) won't work out of the box on node several functions were globalized and browserfied for running in a browser.

If you want to do this in node; check out the examples in the examples directory of the project and those run fine from node.      Most people run it from node; and the browser is just used as a testing bed to show you what it can do without installing anything, but it has several things that have to be pre-setup to make work properly in a browser vs how it works in Node.

**Comment by johntom** [comment]
Thanks.
Making very good progress and yes I only want to run from node, I crreated a report today that has one title page, many detail pages each showing header info and one final footer. While it took a while to figure it out, It works perfectly!
Thanks for this great solution. I be porting all my phantom/handlebars code asap. Also forgot that I used your fluentjs way back for a sails 9 app.
John
